name: example
description: Rx Shared Preferences example.
version: 3.0.0
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_provider: ^2.1.0
  rx_shared_preferences:

dependency_overrides:
  rx_shared_preferences:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
