name: rx_shared_preferences
description: Rxdart streaming shared preferences. Reactive stream rxdart wrapper around SharedPreferences. A stream based wrapper over shared_preferences, allowing reactive key-value storage.
version: 3.1.0
homepage: https://github.com/hoc081098/rx_shared_preferences.git
repository: https://github.com/hoc081098/rx_shared_preferences.git
issue_tracker: https://github.com/hoc081098/rx_shared_preferences/issues
funding:
  - https://www.buymeacoffee.com/hoc081098

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

topics:
  - rxdart
  - hoc081098
  - rx-shared-preferences
  - reactive-shared-preferences
  - reactive-programming

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.2
  rx_storage: ^3.0.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  shared_preferences_platform_interface: 2.2.0
  plugin_platform_interface: 2.1.4
  collection: ^1.16.0
